### ISSUE TITLE
Does not find topics

### ISSUE THREAD

**Issue by Annalein214** [piuswalter/StudySmarter-Slides-Exporter#7]
I assume the software is incompatible after changes in the webpage. 
It does not find the topics. When I add the topic name manually in the code, it downloads an empty json File? 
My JS is rusty. It would be great, if you could help me to adjust the code.

**Comment by piuswalter** [comment]
Hello @Annalein214,
sure, i will look into it and get back to you as soon as i get it fixed.
What do you need the JSON file for? Have you already seen [StudyOffline](https://github.com/piuswalter/StudyOffline)? There you can download all subjects and flashcards and study them offline on your smartphone.

**Comment by Annalein214** [comment]
Ah great, yes I want to have the cards offline. I will look into the other tool. Thank you. 
BTW for a stupid, like me, maybe you could add in the Readme, that you need to open the JS console on the studysmarter webpage (and which one) and only then the script works. Otherwise you get errors.

**Comment by piuswalter** [comment]
Hello @Annalein214,
I fixed the bugs and adapted the README file. Please try again to download the JSON files you need.
If there are some questions, feel free to open the issue and ask again.
